[tools]
go = "latest"
ripgrep = "latest"
zoxide = "latest"
ghq = "latest"
fzf = "latest"
lazygit = "latest"
delta = "latest"
yazi = "latest"
node = "latest"
lua-language-server = "latest"
fd = "latest"
github-cli = "latest"
"npm:typescript-language-server" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
tmux = "latest"
rust = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@github/copilot-language-server" = "latest"
python = "latest"
# "aqua:neovim" = "latest"
lua = "latest"
"npm:@openai/codex" = "latest"
"asdf:neovim" = "nightly"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]
